# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TasteE' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TasteE
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'TasteETests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TasteE-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TasteE-tvOS

  target 'TasteE-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
