// export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';
// export const ADD_RECIPE = 'ADD_RECIPE';
// export const SET_FULL_VIEW_DIMENSIONS = 'SET_FULL_VIEW_DIMENSIONS';
export const FETCH_HOTEL_LOADING = 'FETCH_HOTEL_LOADING';
export const SET_HOTEL_DETAILS = 'SET_HOTEL_DETAILS';
export const FETCH_HOTEL_ERROR = 'FETCH_HOTEL_ERROR';
export const EXCEPTION = 'EXCEPTION';
export const CLEAR_EXCEPTION_MSG = 'CLEAR_EXCEPTION_MSG';
export const SET_DISH_LIST = 'SET_DISH_LIST';
export const SET_MODIFIED_DISH_LIST = 'SET_MODIFIED_DISH_LIST';
export const DISH_LIST_LOADING = 'DISH_LIST_LOADING';
export const DISH_LIST_ERROR = 'DISH_LIST_ERROR';

export const SET_MENU_SEARCH_VALUE = 'MENU_SEARCH';
export const SET_MENU_SEARCH_ACTIVE = 'MENU_SEARCH_ACTIVE';
export const SET_MENU_SEARCH_INACTIVE = 'MENU_SEARCH_INACTIVE';

export const SET_FAV_SEARCH_VALUE = 'FAV_SEARCH';
export const SET_FAV_SEARCH_ACTIVE = 'FAV_SEARCH_ACTIVE';
export const SET_FAV_SEARCH_INACTIVE = 'FAV_SEARCH_INACTIVE';

export const FETCH_HOTEL_DETAIL = "FETCH_HOTEL_DETAIL";
export const FETCH_HOTEL_DETAIL_LOADING = "FETCH_HOTEL_DETAIL_LOADING";
export const FETCH_HOTEL_DETAIL_ERROR = "ERROR_FETCH_HOTEL_DETAIL";