export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const SET_FULL_VIEW_DIMENSIONS = 'SET_FULL_VIEW_DIMENSIONS';
export const FETCH_HOTEL_LOADING = 'FETCH_HOTEL_LOADING';
export const SET_HOTEL_DETAILS = 'SET_HOTEL_DETAILS';
